### ISSUE TITLE
How to run this project

### ISSUE THREAD

**Issue by gongshaotian** [eshentw/Fast-3D-Human-Pose-Estimation#10]
That's cool!
when will the trainning part be updated? can you provide the requirments documents first? 
thanks🤩

**Comment by eddie0509tw** [comment]
Thks for your following! I've updated the temporary instruction and requirement for training. It's relatively easy to do it once you have the weight and data ready as mention in the readme. 
Please let me know if there's any further problems.

Eddie

**Comment by gongshaotian** [comment]
I successfully reference the results according to readme and successfully trained the CDRNet.
I will study the code and try to extend the two views into multiple views.
You did a great job！
